name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # runs yarn install
      - name: yarn lint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint # runs yarn lint
