on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build: 
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  checks:
    name: 'Terraform Formatting'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.10

    - name: Terraform Format
      working-directory: infra
      run: terraform fmt -check -recursive

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      working-directory: infra/stages/staging
      run: terraform init && terraform plan -no-color
      continue-on-error: true

    - name: Update Pull Request
      uses: actions/github-script@v3
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const commentBody = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
          <details><summary>Show Plan</summary>
          \`\`\`${process.env.PLAN}\`\`\`
          </details>
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

          const {data: comments} = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
            })
    
          // Find any comment already made by the bot.
          const existingComment = comments.find(comment => comment.user.id === 41898282)
          if (existingComment) {
            await github.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existingComment.id,
              body: commentBody
            })
          } else {
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
              body: commentBody
            })
          }

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

  staging_deploy:
    name: Terraform Staging Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/stages/staging
    environment:
      name: Staging
      url: https://thadmin-staging.technicie.nl
    steps:
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform init && terraform apply -auto-approve

  production_deploy:
    name: Terraform Staging Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/stages/production
    environment:
      name: Production
      url: https://thadmin.thalia.nu
    steps:
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform init && terraform apply -auto-approve